name: Validate
on:
  push:
    branches:
      - main
    paths:
      - 'vib-action/*'
  pull_request:
    paths:
      - 'vib-action/*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Compile
      run: npm run build
    - name: npm test
      run: npm test
    - name: Lint
      run: npm run lint
    - name: Format
      run: npm run format-check
